### ISSUE TITLE
Can't  load josm object as ES Module

### ISSUE THREAD

**Issue by pl71** [Gubaer/josm-scripting-plugin#97]
["HelloWorld.js"](https://github.com/Gubaer/josm-scripting-plugin/blob/master/src/main/resources/scripts/HelloWorld.GraalJS.js) sample is running normally. (Use GraalJS, the JavaScript engine provided by the GraalVM)

But,
`import josm from 'josm'`
throws: 
"Error: Error reading: C:\Users\User\Desktop\josm"

Looks like modules in /v3 can't be loaded/accessed.
scripting.jar is in "C:\Users\User\AppData\Roaming\JOSM\plugins"

Using Josm.jar from desktop on Windows 10 through bat file.
`java -jar --module-path "C:\Other\graaljs-22.1.0\lib" --add-modules org.graalvm.sdk,org.graalvm.js,com.oracle.truffle.regex,org.graalvm.truffle "C:\Users\User\Desktop\josm-tested.jar"
`

**Comment by Gubaer** [comment]
Can reproduce and confirm. Will have to insert additional log messages and analyse what is going wrong on Windows 10.

**Comment by stephankn** [comment]
I am also affected. Plugin not usable like this. As it is unresolved since half a year: How can I support to track this down?
Maybe related: extracting the v3 folder and adding it to the configuration as es modules will lead to the plugin searching for the josm module at even another non-existing location D:\es-module-repo\6ba5091e-5fe2-4445-8ded-873fcb00ca19\josm.mjs

**Comment by stephankn** [comment]
Plugin has some exceptions on startup, which sound related to me:
```
2023-03-24 20:14:06.084 INFO: loading plugin 'scripting' (version v0.2.7)
2023-03-24 20:14:06.131 WARNING: Failed to create URI referring to the CommonJS modules in the plugin jar. Cannot load CommonJS modules for v2 API from the plugin jar.
java.net.URISyntaxException: Illegal character in opaque part at index 13: jar:file://C:\Users\xxx\AppData\Roaming\JOSM\plugins\scripting.jar!/js/v2
        at java.base/java.net.URI$Parser.fail(URI.java:2974)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
        at java.base/java.net.URI$Parser.parse(URI.java:3181)
        at java.base/java.net.URI.<init>(URI.java:623)
        at org.openstreetmap.josm.plugins.scripting.graalvm.ModuleJarURI.buildJarUri(ModuleJarURI.java:45)
        at org.openstreetmap.josm.plugins.scripting.graalvm.commonjs.CommonJSModuleRepositoryRegistry.buildRepositoryUrlForBuiltinModules(CommonJSModuleRepositoryRegistry.java:45)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.initGraalVMJSModuleRepository(ScriptingPlugin.java:72)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.<init>(ScriptingPlugin.java:115)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.<init>(ScriptingPlugin.java:104)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:382)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:813)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:898)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:950)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1247)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:962)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)

2023-03-24 20:14:06.142 WARNING: Failed to create URI referring to the ES Modules in the plugin jar. Cannot load ES Modules for API V3 from the plugin jar file.
java.net.URISyntaxException: Illegal character in opaque part at index 13: jar:file://C:\Users\xxx\AppData\Roaming\JOSM\plugins\scripting.jar!/js/v3
        at java.base/java.net.URI$Parser.fail(URI.java:2974)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
        at java.base/java.net.URI$Parser.parse(URI.java:3181)
        at java.base/java.net.URI.<init>(URI.java:623)
        at org.openstreetmap.josm.plugins.scripting.graalvm.ModuleJarURI.buildJarUri(ModuleJarURI.java:45)
        at org.openstreetmap.josm.plugins.scripting.graalvm.esmodule.ESModuleResolver.buildRepositoryUrlForBuiltinModules(ESModuleResolver.java:72)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.initGraalVMESModuleRepositories(ScriptingPlugin.java:88)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.<init>(ScriptingPlugin.java:116)
        at org.openstreetmap.josm.plugins.scripting.ScriptingPlugin.<init>(ScriptingPlugin.java:104)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:382)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:813)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:898)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:950)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1247)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:962)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
```

**Comment by stephankn** [comment]
I guess the problem is, that the windows path in not a valid URI. If fails on the path. Not certain whether index is 0-based. So either colon or backslash.

I guess this location needs preprocessing of the path to jar:

https://github.com/Gubaer/josm-scripting-plugin/blob/c5477a7a2efae39ad69c7b2a4b29c29032da7d9c/src/main/java/org/openstreetmap/josm/plugins/scripting/graalvm/ModuleJarURI.java#L46

The name need likely being converted to a valid URI before being used, eg

```
File f = new File("C:\Users\xxx\AppData\Roaming\JOSM\plugins\scripting.jar");
URI u = f.toURI();
```

**Comment by stephankn** [comment]
replacing the format string like this returns a valid URI,

```
"jar:{0}!{1}", new File(jarFilePath).toURI(), jarEntryPath
```

This fixes for me the exception at startup. Still the module is not found. Maybe the format is not suitable for opening it later? I don't know where this happens later and I probably have no longer the energy trying to dig into the source code to find the related area.

@Gubaer I hope this helps you to figure out where the registration of the module path fails later.

**Comment by stephankn** [comment]
I continued to debug a bit. It seems that the conversion between FILE or Path to Strings and back is leading to problems with java later interpreting the separator character of Windows "\" as a escape character.

`resolveZipEntryPath` did not find the entry in the jar. So another fix on top of the above URI fix was to replace all backslash to forward slash before trying to find the entry in the jar. This results then in found entries as opposed to the null returned earlier.
Better would probably be to not cast into string but stick with the file-system aware classes. 

This results now in a similar message than I had when specifying the module directly: "Error: Error reading: D:\es-module-repo\15ecb279-2371-42eb-924e-a61315a9a865\josm". As this path has again backslashes, I suspect a similar problem at another area.

**Comment by pl71** [comment]
@Gubaer @stephankn Could you please advise how to access logger output from the plugin?

**Comment by pl71** [comment]
@stephankn 
> This results now in a similar message than I had when specifying the module directly: "Error: Error reading: D:\es-module-repo\15ecb279-2371-42eb-924e-a61315a9a865\josm". As this path has again backslashes, I suspect a similar problem at another area.

`@Override
    public @NotNull SeekableByteChannel newByteChannel(@NotNull Path absolutePath)  ...`

270: `final var zipEntry = jar.getEntry(zipEntryPath.toString().replaceAll("\\\\", "/"));`
otherwise, `getEntry` will return `null`.

See my PR  #103

**Comment by Gubaer** [comment]
> replacing the format string like this returns a valid URI,
> 
> ```
> "jar:{0}!{1}", new File(jarFilePath).toURI(), jarEntryPath
> ```
> 
> This fixes for me the exception at startup. Still the module is not found. Maybe the format is not suitable for opening it later? I don't know where this happens later and I probably have no longer the energy trying to dig into the source code to find the related area.
> 
> @Gubaer I hope this helps you to figure out where the registration of the module path fails later.
@stephankn: thanks for your analysis, this is helpful. I have some free capacity in july and will send part of it on this issue.

**Comment by Gubaer** [comment]
First step: I've created a testing environment for interactively testing JOSM and the scripting plugin with different JOSM, JDK, GraalVM, and GraalJS versions, see [commit](https://github.com/Gubaer/josm-scripting-plugin/commit/cbcafe441c38191e792f13a0a84087a3ecaf2c1c)

**Comment by pl71** [comment]
Thank you.
I will check it and revert.

Regards,

Plamen

     On Tuesday, July 4, 2023 at 04:32:21 PM GMT+3, Gubaer ***@***.***> wrote:  
 
 


First step: I've created a testing environment for interactively testing JOSM and the scripting plugin with different JOSM, JDK, GraalVM, and GraalJS versions, see commit

**Comment by Gubaer** [comment]
Second step: all unit tests now pass on the Windows platform. The build on the branch [97-esmodules-on-win10-2](https://github.com/Gubaer/josm-scripting-plugin/tree/97-esmodules-on-win10-2) should now work more reliably on Windows. 

Please give it a try. There is also a new [testing environment](https://github.com/Gubaer/josm-scripting-plugin/tree/97-esmodules-on-win10-2/testing/windows) to interactively test JOMS and the scripting plugin with different JDKs and GraalJS, or with a GraalVM distribution.

**Comment by pl71** [comment]
.\josm.ps1 -josm latest -graalJs latest

with script:

    import josm from 'josm'

Result:

    Error: Error reading: C:\Users\User\git\G-JSP\testing\windows\josm

Stack Trace:

    org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMEvalException: failed to eval script
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacade.eval(GraalVMFacade.java:184)
	at org.openstreetmap.josm.plugins.scripting.ui.ScriptExecutor.lambda$runScriptWithGraalEngine$2(ScriptExecutor.java:243)
	at org.openstreetmap.josm.plugins.scripting.ui.ScriptExecutor.runOnSwingEDT(ScriptExecutor.java:108)
	at org.openstreetmap.josm.plugins.scripting.ui.ScriptExecutor.runScriptWithGraalEngine(ScriptExecutor.java:250)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsolePanel$RunScriptAction.actionPerformed(ScriptingConsolePanel.java:236)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	...

**Comment by pl71** [comment]
`java\org\openstreetmap\josm\plugins\scripting\graalvm\esmodule\JarESModuleRepository.java` needs to be corrected also, see my PR.

**Comment by Gubaer** [comment]
I can't reproduce this error in my testing environment. The following basic script which uses ES modules from API V3 runs on all relevant configurations:

```javascript
import josm from 'josm'
import * as console from 'josm/scriptingconsole'
console.println(josm.version)
```
* **OK** for GraalVM with JDK11 and JOSM latest
* **OK** for GraalVM with JDK17 and JOSM latest
*  **OK** for OpenJDK11 with latest GraalJS and JOSM latest
* **OK** for OpenJDK17 with latest GraalJS and JOSM latest

To tests the latest scriping plugin build on branch `97-esmodules-on-win10-2` you have to run the following steps:

```powershell
# clone the git repo on this branch. Or use other git command such that the latest
# state of branch 97-esmodules-on-win10-2 is available locally
git clone --branch 97-esmodules-on-win10-2 git@github.com:Gubaer/josm-scripting-plugin.git
cd josm-scripting-plugin

# build the scripting plugin jar without running unit and functioncal tests. Running tests takes
# a couple of minutes.
.\gradlew.bat assemble

# go to the testing environment
cd testing/windows

# prepare the testing environment
.\manage.ps1 download-josm latest
.\manage.ps1 download-jdk jdk11
.\manage.ps1 download-jdk jdk17
.\manage.ps1 download-graalvm jdk11
.\manage.ps1 download-graalvm jdk17
.\manage.ps1 download-graaljs
.\manage.ps1 create-josm-home

# install the locally built scripting.jar into 'josm-home'
.\manage.ps1 update-scripting-jar

# now launch JOSM for one of the relevant configurations. This example lauches
# JOSM latest with the GraalVM for JDK 11
.\josm.ps1 -josm latest -jdk jdk11 -useGraalVM

# then open the scripting console, enter/load a script, and run it
```

**Comment by pl71** [comment]
.\josm.ps1 -josm latest -jdk jdk11 -useGraalVM  ---- **OK**
     .\josm.ps1 -josm latest -jdk jdk17 -useGraalVM  ---- **OK**

With simple "Hello world" scripts as above.

Though the following is still not implemented:
    .\manage.ps1 prepare

**Comment by Gubaer** [comment]
> Though the following is still not implemented: .\manage.ps1 prepare

Argh, right, I forgot to push the commit! 😞  It should be available now on the branch `97-esmodules-on-win10-2`.

**Comment by Gubaer** [comment]
**Update**: I plan to release version v0.2.9 next week. It will include the fixes on branch `97-esmodules-on-win10-2`. 

With release v0.2.9, using GraalVM or GraalJS with API V3 on the Windows platform should be possible. The plugin should successfully load the API V3 ES modules from the scripting plugin jar file. Let me know if you are aware of use cases where loading ES modules of API V3 fails on the branch `97-esmodules-on-win10-2`.

However, I'm aware there are still problems loading **custom ES modules** from **custom ES module repositories** (file system or jar file). In the current version (and in the next version, v0.2.9), the scripting plugin relies on [java.nio.file.Path](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html) to manipulate relative paths. `java.nio.file.Path` turned out to be too fragile because it behaves differently on the Unix and the Windows platform
and because the `resolve` method assumes that the resolution context is a directory.

I, therefore, implemented a custom [RelativePath](https://github.com/Gubaer/josm-scripting-plugin/blob/relative-path/src/main/java/org/openstreetmap/josm/plugins/scripting/model/RelativePath.java) and started to migrate the code base to it on branch [relative-path](https://github.com/Gubaer/josm-scripting-plugin/tree/relative-path).

As soon as this migration is completed and the unit tests pass on the Linux and Windows platforms, I will publish the next release, v0.2.10.

**Comment by pl71** [comment]
Yes, I noticed some issues with repositories specified in Settings/Scripting. 
Nice to have - monospace font in stack console log - it would be much easier to locate problems.

**Comment by Gubaer** [comment]
I today published release [v0.2.9](https://github.com/Gubaer/josm-scripting-plugin/releases/tag/v0.2.9)

**Comment by Gubaer** [comment]
**Update**: Migration to [RelativePath](https://github.com/Gubaer/josm-scripting-plugin/blob/relative-path/src/main/java/org/openstreetmap/josm/plugins/scripting/model/RelativePath.java) is completed

Loading standard (provided by the scripting plugin itself) and custom (implemented by you) ES modules should now be more reliable.

* all unit tests pass, both on the Windows and the UNIX platform 
* there are some [sample modules](https://github.com/Gubaer/josm-scripting-plugin/tree/relative-path/src/test/resources/sample-modules) with an internal structure and mutual interdependencies. These [automated test cases](https://github.com/Gubaer/josm-scripting-plugin/blob/relative-path/src/test/functional/groovy/org/openstreetmap/josm/plugins/scripting/esmodules/ESModuleUsageTest.groovy) load and use them successfully.

Please give it a try and let me know if you still need help with problems.

Next week I will merge the branch [relative-path](https://github.com/Gubaer/josm-scripting-plugin/tree/relative-path) to `master` and release v0.2.10.

**Comment by Gubaer** [comment]
I today published release [v0.2.10](https://github.com/Gubaer/josm-scripting-plugin/releases/tag/v0.2.10). It includes fixes for this issue.
